### ISSUE TITLE
Not Working IOS

### ISSUE THREAD

**Issue by nduc86686** [llfbandit/record#231]
**Package version**
record: ^5.0.1

**Describe the bug**
flutter: PlatformException(record, Failed to start recording, setPreferredInputNumberOfChannels: The operation couldn’t be completed. (OSStatus error -50.), null)

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by llfbandit** [comment]
Should be fixed in `record_darwin: ^1.0.1-beta.1`. You will need to add it manually to test it.

**Comment by nduc86686** [comment]
i used the version you provided but it still doesn't work,specific error:
`flutter: wav supported: true
flutter: [      id: Built-In Microphone
flutter:       label: iPhone Micrô
flutter:       ]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(record, Failed to start recording, setPreferredInputNumberOfChannels: The operation couldn’t be completed. (OSStatus error -50.), null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      AudioRecorder.start (package:record/src/record.dart:60:5)
<asynchronous suspension>`

**Comment by EvertonMJunior** [comment]
This is not yet solved as of 1.0.1-beta.1. By not throwing the error, the audio is recorded just fine. In current tests, it appears to be related to a previous audio session of a video recording or a video playback. Still investigating

**Comment by llfbandit** [comment]
Released in record_darwin 1.0.1

**Comment by adnan-haider007** [comment]
Unhandled Exception: PlatformException(record, The operation couldn’t be completed. (OSStatus error 1718449215.), null, null)
i am facing this issue

**Comment by PhuCG** [comment]
I have same issuse
Platform IOS
Device 12 Promax
Version 17.5.1

In my app
Flutter version: 3.24
Record 5.1.2

This error log when i call function record with `stream`.
`PlatformException (PlatformException(record, Failed to start recording, setPreferredInputNumberOfChannels: The operation couldn’t be completed. (OSStatus error -50.), null))`

**Comment by AseemWangoo** [comment]
Future<String> _getPath() async {
    final dir = await getApplicationDocumentsDirectory();

    if (Platform.isIOS) {
      return path.join(
        dir.path,
        'audio.m4a',
      );
    }

    return path.join(
      dir.path,
      'audio.wav',
    );
  }
  
  this is the fix
